FROM php:8.3-fpm

WORKDIR /var/www

RUN apt-get update && apt-get install -y \
    git \
    curl \
    zip \
    unzip \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libonig-dev \
    libxml2-dev \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Skopíruj len potrebné súbory na inštaláciu composer závislostí
COPY composer.json artisan ./
COPY bootstrap/ bootstrap/
COPY config/ config/
COPY routes/ routes/

# Composer install (už by mal prebehnúť správne)
RUN composer install --prefer-dist --no-dev --optimize-autoloader

# Skopíruj zvyšok projektu
COPY . .

# Práva
RUN chmod -R 775 storage bootstrap/cache \
 && chown -R www-data:www-data /var/www

EXPOSE 9000

CMD ["php-fpm"]
